apiVersion: vpc.opentelekomcloud.crossplane.io/v1alpha1
kind: SecondaryCidrV3
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/secondarycidrv3
  labels:
    testing.upbound.io/example-name: secondary
  name: secondary
spec:
  forProvider:
    cidrs:
    - 23.9.0.0/16
    - 23.10.0.0/16
    - 23.11.0.0/16
    vpcId: ${opentelekomcloud_vpc_v1.vpc.id}

---

apiVersion: vpc.opentelekomcloud.crossplane.io/v1alpha1
kind: VpcV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/secondarycidrv3
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidr: 192.168.0.0/16
    name: tf_vpc
