apiVersion: vpc.crossplane.io/v1alpha1
kind: V1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/v1
  labels:
    testing.upbound.io/example-name: vpc_v1
  name: vpc-v1
spec:
  forProvider:
    cidr: ${var.vpc_cidr}
    name: ${var.vpc_name}
