apiVersion: vpc.opentelekomcloud.crossplane.io/v1alpha1
kind: VpcV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/v1
  labels:
    testing.upbound.io/example-name: sample-lb
  name: sample-lb
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    name: crossplane-vpc
    tags:
      managed-by: crossplane
---

apiVersion: vpc.opentelekomcloud.crossplane.io/v1alpha1
kind: SubnetV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/subnetv1
  labels:
    testing.upbound.io/example-name: sample-lb
  name: sample-lb
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    gatewayIp: "192.168.0.1"
    name: crossplane-subnet
    ntpAddresses: "10.100.0.33,10.100.0.34"
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-lb
    tags:
      managed-by: crossplane

---

apiVersion: vpc.opentelekomcloud.crossplane.io/v1alpha1
kind: EIPV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/eipv1
  labels:
    testing.upbound.io/example-name: sample-lb
  name: sample-lb
spec:
  forProvider:
    bandwidth:
      - chargeMode: traffic
        name: crossplane-lb-instance
        shareType: PER
        size: 8
    publicip:
      - type: 5_bgp

---

apiVersion: lb.opentelekomcloud.crossplane.io/v1alpha1
kind: LoadbalancerV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/loadbalancerv3
  labels:
    testing.upbound.io/example-name: sample-lb
  name: sample-lb
spec:
  forProvider:
    name: crossplane-lb
    availabilityZones:
      - eu-de-01
    networkIdsRefs:
      - name: sample-lb
    routerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-lb
    publicIp:
      - idSelector:
          matchLabels:
            testing.upbound.io/example-name: sample-lb
    tags:
      managed-by: crossplane
