apiVersion: vpc.opentelekomcloud.crossplane.io/v1alpha1
kind: VpcV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/v1
  labels:
    testing.upbound.io/example-name: sample-lb
  name: sample-lb
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    name: crossplane-vpc
    tags:
      managed-by: crossplane
---

apiVersion: vpc.opentelekomcloud.crossplane.io/v1alpha1
kind: SubnetV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/subnetv1
  labels:
    testing.upbound.io/example-name: sample-lb
  name: sample-lb
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    gatewayIp: "192.168.0.1"
    name: crossplane-subnet
    ntpAddresses: "10.100.0.33,10.100.0.34"
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-lb
    tags:
      managed-by: crossplane

---

apiVersion: lb.opentelekomcloud.crossplane.io/v1alpha1
kind: LoadbalancerV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/loadbalancerv3
  labels:
    testing.upbound.io/example-name: sample-lb
  name: sample-lb
spec:
  forProvider:
    name: crossplane-lb
    availabilityZones:
      - eu-de-01
    networkIdsRefs:
      - name: sample-lb
    routerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-lb
    tags:
      managed-by: crossplane

---

apiVersion: lb.opentelekomcloud.crossplane.io/v1alpha1
kind: ListenerV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/listenerv3
  labels:
    testing.upbound.io/example-name: sample-lb
  name: sample-lb
spec:
  forProvider:
    name: crossplane-listener
    loadbalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-lb
    protocol: HTTP
    protocolPort: 8080
    tags:
      managed-by: crossplane


---

apiVersion: lb.opentelekomcloud.crossplane.io/v1alpha1
kind: PoolV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/memberv3
  labels:
    testing.upbound.io/example-name: sample-lb
  name: sample-lb
spec:
  forProvider:
    lbAlgorithm: ROUND_ROBIN
    loadbalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-lb
    name: crossplane-pool
    protocol: HTTP

---

apiVersion: lb.opentelekomcloud.crossplane.io/v1alpha1
kind: PolicyV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/policyv3
  labels:
    testing.upbound.io/example-name: sample-lb
  name: sample-lb
spec:
  forProvider:
    action: REDIRECT_TO_POOL
    listenerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-lb
    position: 37
    redirectPoolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-lb

---

apiVersion: lb.opentelekomcloud.crossplane.io/v1alpha1
kind: RuleV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/rulev3
  labels:
    testing.upbound.io/example-name: sample-lb
  name: sample-lb
spec:
  forProvider:
    compareType: REGEX
    policyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-lb
    type: PATH
    value: ^.+$
