apiVersion: sfs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: FileSystemV2
metadata:
  annotations:
    meta.upbound.io/example-id: sfs/v1alpha1/filesystemv2
  labels:
    testing.upbound.io/example-name: share-file
  name: sfs-fs-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    description: xptest
    name: sfs-fs-${Rand.RFC1123Subdomain}
    shareProto: NFS
    size: 50
    tags:
      muh: kuh