apiVersion: sfs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: ShareAccessRulesV2
metadata:
  annotations:
    meta.upbound.io/example-id: sfs/v1alpha1/shareaccessrulesv2
  labels:
    testing.upbound.io/example-name: sfs_rules
  name: sfs-ar-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    accessRule:
      - accessLevel: rw
        accessToSelector:
          matchLabels:
            testing.upbound.io/example-name: vpc_1
        accessType: cert
    shareSelector:
      matchLabels:
        testing.upbound.io/example-name: sfs_1

---
apiVersion: sfs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: FileSystemV2
metadata:
  annotations:
    meta.upbound.io/example-id: sfs/v1alpha1/shareaccessrulesv2
  labels:
    testing.upbound.io/example-name: sfs_1
  name: sfs-fs-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    description: xp-test
    name: sfs-fs-${Rand.RFC1123Subdomain}
    shareProto: NFS
    size: 50

---
apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: VpcV1
metadata:
  annotations:
    meta.upbound.io/example-id: sfs/v1alpha1/shareaccessrulesv2
  labels:
    testing.upbound.io/example-name: vpc_1
  name: sfs-vpc-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    cidr: 192.168.0.0/16
    name: sfs-vpc-${Rand.RFC1123Subdomain}