apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: VpcV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/v1
  labels:
    testing.upbound.io/example-name: example-vpc
  name: sfs-vpc-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    name: sfs-vpc-${Rand.RFC1123Subdomain}
    tags:
      managed-by: crossplane
---
apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: SubnetV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/subnetv1
  labels:
    testing.upbound.io/example-name: example-subnet
  name: sfs-stn-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    gatewayIp: "192.168.0.1"
    name: sfs-stn-${Rand.RFC1123Subdomain}
    ntpAddresses: "10.100.0.33,10.100.0.34"
    vpcSelector:
      matchLabels:
        testing.upbound.io/example-name: example-vpc
    tags:
      managed-by: crossplane
---
apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: SecgroupV3
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/secgroupv3
  labels:
    testing.upbound.io/example-name: example-sg
  name: sfs-sg-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    description: My VPC security group
    name: sfs-sg-${Rand.RFC1123Subdomain}

---
apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: SecgroupRuleV3
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/secgrouprulev3
  labels:
    testing.upbound.io/example-name: rule_1
  name: rule-1
  namespace: test
spec:
  forProvider:
    action: allow
    description: some basic security rule
    direction: ingress
    multiPort: "1-60000"
    protocol: "255"
    priority: 1
    securityGroupSelector:
      matchLabels:
        testing.upbound.io/example-name: example-sg

---
apiVersion: sfs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: TurboShareV1
metadata:
  annotations:
    meta.upbound.io/example-id: sfs/v1alpha1/turbosharev1
  labels:
    testing.upbound.io/example-name: sfs-turbo
  name: sfs-tbo-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    availabilityZone: eu-de-01
    name: sfs-tbo-${Rand.RFC1123Subdomain}
    secgroupSelector:
      matchLabels:
        testing.upbound.io/example-name: example-sg
    shareProto: NFS
    size: 500
    subnetSelector:
      matchLabels:
        testing.upbound.io/example-name: example-subnet
    vpcSelector:
      matchLabels:
        testing.upbound.io/example-name: example-vpc