// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AssociationV3) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FlowLogV3) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *InstanceV3) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropagationV3) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RouteTableV3) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StaticRouteV3) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VPCAttachmentV3) Hub() {}
