apiVersion: networking.crossplane.io/v1alpha1
kind: NetworkV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/networkv2
  labels:
    testing.upbound.io/example-name: network_1
  name: network-1
spec:
  forProvider:
    adminStateUp: "true"
    name: network_1

---

apiVersion: compute.crossplane.io/v1alpha1
kind: InstanceV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/networkv2
  labels:
    testing.upbound.io/example-name: instance_1
  name: instance-1
spec:
  forProvider:
    name: instance_1
    network:
    - port: ${opentelekomcloud_networking_port_v2.port_1.id}
    securityGroupsRefs:
    - name: secgroup_1

---

apiVersion: compute.crossplane.io/v1alpha1
kind: SecgroupV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/networkv2
  labels:
    testing.upbound.io/example-name: secgroup_1
  name: secgroup-1
spec:
  forProvider:
    description: a security group
    name: secgroup_1
    rule:
    - cidr: 0.0.0.0/0
      fromPort: 22
      ipProtocol: tcp
      toPort: 22

---

apiVersion: networking.crossplane.io/v1alpha1
kind: PortV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/networkv2
  labels:
    testing.upbound.io/example-name: port_1
  name: port-1
spec:
  forProvider:
    adminStateUp: "true"
    fixedIp:
    - ipAddress: 192.168.199.10
      subnetId: ${opentelekomcloud_networking_subnet_v2.subnet_1.id}
    name: port_1
    networkId: ${opentelekomcloud_networking_network_v2.network_1.id}
    securityGroupIds:
    - ${opentelekomcloud_compute_secgroup_v2.secgroup_1.id}

---

apiVersion: networking.crossplane.io/v1alpha1
kind: SubnetV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/networkv2
  labels:
    testing.upbound.io/example-name: subnet_1
  name: subnet-1
spec:
  forProvider:
    cidr: 192.168.199.0/24
    ipVersion: 4
    name: subnet_1
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: network_1
