apiVersion: lb.opentelekomcloud.crossplane.io/v1alpha1
kind: MonitorV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/monitorv3
  labels:
    testing.upbound.io/example-name: monitor
  name: monitor
spec:
  forProvider:
    delay: 3
    maxRetries: 5
    maxRetriesDown: 1
    monitorPort: 8080
    poolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: pool
    timeout: 30
    type: HTTP

---

apiVersion: lb.opentelekomcloud.crossplane.io/v1alpha1
kind: LoadbalancerV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/monitorv3
  labels:
    testing.upbound.io/example-name: lb
  name: lb
spec:
  forProvider:
    availabilityZones:
    - ${var.availability_zone}
    name: loadbalancer_1
    networkIdsRefs:
    - name: opentelekomcloud_vpc_subnet_v1
    routerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: opentelekomcloud_vpc_subnet_v1

---

apiVersion: lb.opentelekomcloud.crossplane.io/v1alpha1
kind: PoolV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/monitorv3
  labels:
    testing.upbound.io/example-name: pool
  name: pool
spec:
  forProvider:
    lbAlgorithm: ROUND_ROBIN
    loadbalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: lb
    protocol: HTTP
