apiVersion: lb.opentelekomcloud.crossplane.io/v1alpha1
kind: MonitorV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/monitorv3
  labels:
    testing.upbound.io/example-name: monitor
  name: monitor
spec:
  forProvider:
    delay: 3
    maxRetries: 5
    maxRetriesDown: 1
    monitorPort: 8080
    poolId: ${opentelekomcloud_lb_pool_v3.pool.id}
    timeout: 30
    type: HTTP

---

apiVersion: lb.opentelekomcloud.crossplane.io/v1alpha1
kind: LoadbalancerV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/monitorv3
  labels:
    testing.upbound.io/example-name: lb
  name: lb
spec:
  forProvider:
    availabilityZones:
    - ${var.availability_zone}
    name: loadbalancer_1
    networkIds:
    - ${data.opentelekomcloud_vpc_subnet_v1.shared_subnet.network_id}
    routerId: ${data.opentelekomcloud_vpc_subnet_v1.shared_subnet.vpc_id}

---

apiVersion: lb.opentelekomcloud.crossplane.io/v1alpha1
kind: PoolV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/monitorv3
  labels:
    testing.upbound.io/example-name: pool
  name: pool
spec:
  forProvider:
    lbAlgorithm: ROUND_ROBIN
    loadbalancerId: ${opentelekomcloud_lb_loadbalancer_v3.lb.id}
    protocol: HTTP
