apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: SubnetV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/subnetv1
  labels:
    testing.upbound.io/example-name: subnet_v1
  name: subnet-v1
  namespace: upbound-system
spec:
  forProvider:
    cidr: ${var.subnet_cidr}
    gatewayIp: ${var.subnet_gateway_ip}
    name: ${var.subnet_name}
    ntpAddresses: 10.100.0.33,10.100.0.34
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc_v1

---

apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: VpcV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/subnetv1
  labels:
    testing.upbound.io/example-name: vpc_v1
  name: vpc-v1
  namespace: upbound-system
spec:
  forProvider:
    cidr: ${var.vpc_cidr}
    name: ${var.vpc_name}
