/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AsyncInvokeConfigV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EventV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FunctionV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TriggerV2) Hub() {}
