apiVersion: sfs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: ShareAccessRulesV2
metadata:
  annotations:
    meta.upbound.io/example-id: sfs/v1alpha1/shareaccessrulesv2
  labels:
    testing.upbound.io/example-name: sfs_rules
  name: sfs-rules
  namespace: upbound-system
spec:
  forProvider:
    accessRule:
    - accessLevel: rw
      accessTo: ${opentelekomcloud_vpc_v1.vpc_1.id}
      accessType: cert
    - accessLevel: rw
      accessTo: ${opentelekomcloud_vpc_v1.vpc_2.id}
      accessType: cert
    shareId: ${opentelekomcloud_sfs_file_system_v2.sfs_1.id}

---

apiVersion: sfs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: FileSystemV2
metadata:
  annotations:
    meta.upbound.io/example-id: sfs/v1alpha1/shareaccessrulesv2
  labels:
    testing.upbound.io/example-name: sfs_1
  name: sfs-1
  namespace: upbound-system
spec:
  forProvider:
    description: ${var.share_description}
    name: ${var.share_name}
    shareProto: NFS
    size: 50

---

apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: VpcV1
metadata:
  annotations:
    meta.upbound.io/example-id: sfs/v1alpha1/shareaccessrulesv2
  labels:
    testing.upbound.io/example-name: vpc_1
  name: vpc-1
  namespace: upbound-system
spec:
  forProvider:
    cidr: 192.168.0.0/16
    name: sfs_share_vpc_1

---

apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: VpcV1
metadata:
  annotations:
    meta.upbound.io/example-id: sfs/v1alpha1/shareaccessrulesv2
  labels:
    testing.upbound.io/example-name: vpc_2
  name: vpc-2
  namespace: upbound-system
spec:
  forProvider:
    cidr: 192.168.0.0/16
    name: sfs_share_vpc_2
