apiVersion: networking.opentelekomcloud.crossplane.io/v1alpha1
kind: NetworkV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/routerinterfacev2
  labels:
    testing.upbound.io/example-name: sample-network
  name: sample-network
spec:
  forProvider:
    adminStateUp: "true"
    name: crossplane_network

---

apiVersion: networking.opentelekomcloud.crossplane.io/v1alpha1
kind: RouterV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/routerinterfacev2
  labels:
    testing.upbound.io/example-name: sample-router
  name: sample-router
spec:
  forProvider:
    name: crossplane_router

---

apiVersion: networking.opentelekomcloud.crossplane.io/v1alpha1
kind: SubnetV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/routerinterfacev2
  labels:
    testing.upbound.io/example-name: sample-subnet
  name: sample-subnet
spec:
  forProvider:
    name: crossplane_subnet
    cidr: 192.168.199.0/24
    ipVersion: 4
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-network

---

apiVersion: networking.opentelekomcloud.crossplane.io/v1alpha1
kind: RouterInterfaceV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/routerinterfacev2
  labels:
    testing.upbound.io/example-name: router_interface
  name: router-interface
spec:
  forProvider:
    routerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-router
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-subnet
