apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: CredentialV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/credentialv3
  labels:
    testing.upbound.io/example-name: identity-credential
  name: iam-cred-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    description: crossplane
    userSelector:
      matchLabels:
        testing.upbound.io/example-name: identity-credential-user
---
apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: UserV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/userv3
  labels:
    testing.upbound.io/example-name: identity-credential-user
  name: iam-usr-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    name: iam-usr-${Rand.RFC1123Subdomain}
    passwordSecretRef:
      key: example-key
      name: example-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: test
type: Opaque
data:
  example-key: ${data.userKey}
