apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: GroupMembershipV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/groupmembershipv3
  labels:
    testing.upbound.io/example-name: identity-group-membership
  name: iam-grpm-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    groupSelector:
      matchLabels:
        testing.upbound.io/example-name: identity-group-membership-group
    usersSelector:
      matchLabels:
        testing.upbound.io/example-name: identity-group-membership-user

---
apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: GroupV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/groupmembershipv3
  labels:
    testing.upbound.io/example-name: identity-group-membership-group
  name: iam-grp-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    description: crossplane
    name: iam-grp-${Rand.RFC1123Subdomain}

---
apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: UserV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/groupmembershipv3
  labels:
    testing.upbound.io/example-name: identity-group-membership-user
  name: iam-usr-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    enabled: true
    name: iam-usr-${Rand.RFC1123Subdomain}
    passwordSecretRef:
      key: example-key
      name: example-secret

---
apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: UserV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/groupmembershipv3
  labels:
    testing.upbound.io/example-name: identity-group-membership-user
  name: iam-usr-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    enabled: true
    name: iam-usr-${Rand.RFC1123Subdomain}
    passwordSecretRef:
      key: example-key
      name: example-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: test
type: Opaque
data:
  example-key: ${data.userKey}
