apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: PasswordPolicyV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/passwordpolicyv3
  labels:
    testing.upbound.io/example-name: policy_1
  name: iam-pwpl-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    maximumConsecutiveIdenticalChars: 0
    minimumPasswordAge: 5
    minimumPasswordLength: 8
    numberOfRecentPasswordsDisallowed: 1
    passwordCharCombination: 2
    passwordNotUsernameOrInvert: true
    passwordValidityPeriod: 180
