apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: ProtectionPolicyV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/protectionpolicyv3
  labels:
    testing.upbound.io/example-name: identity-protection-policy
  name: iam-prpl-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    enableOperationProtectionPolicy: false
    selfManagement:
      - accessKey: true
        email: false
        mobile: false
        password: true
