apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: ProviderV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/providerv3
  labels:
    testing.upbound.io/example-name: identity-provider
  name: iam-prov-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    description: crossplane
    enabled: true
    name: ACME-${Rand.RFC1123Subdomain}
