apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: RoleAssignmentV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/roleassignmentv3
  labels:
    testing.upbound.io/example-name: role_assignment_1
  name: iam-ra-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    groupSelector:
      matchLabels:
        testing.upbound.io/example-name: group_1
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: project_1
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: role_1