apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: RoleAssignmentV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/roleassignmentv3
  labels:
    testing.upbound.io/example-name: identity-role-assignment
  name: iam-rlas-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    groupSelector:
      matchLabels:
        testing.upbound.io/example-name: identity-role-assn-group
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: identity-role-assn-project
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: identity-role-assn-role

---
apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: GroupV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/roleassignmentv3
  labels:
    testing.upbound.io/example-name: identity-role-assn-group
  name: iam-grp-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    name: iam-grp-${Rand.RFC1123Subdomain}

---
apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: ProjectV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/roleassignmentv3
  labels:
    testing.upbound.io/example-name: identity-role-assn-project
  name: iam-proj-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    name: eu-de_iam-proj-${Rand.RFC1123Subdomain}

---
apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: RoleV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/rolev3
  labels:
    testing.upbound.io/example-name: identity-role-assn-role
  name: iam-role-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    description: role
    displayLayer: domain
    displayName: iam-role-${Rand.RFC1123Subdomain}
    statement:
      - action:
          - obs:bucket:GetBucketAcl
        condition: |2
            {
              "StringStartWith": {
                  "g:ProjectName": [
                      "eu-de"
                  ]
              },
              "StringNotEqualsIgnoreCase": {
                  "g:ServiceName": [
                      "iam"
                  ]
              }
            }
        effect: Allow
        resource:
          - OBS:*:*:bucket:test-bucket
      - action:
          - obs:bucket:HeadBucket
          - obs:bucket:ListBucketMultipartUploads
          - obs:bucket:ListBucket
        effect: Allow
