apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: UserGroupMembershipV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/usergroupmembershipv3
  labels:
    testing.upbound.io/example-name: membership_1
  name: iam-um-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    groupsSelector:
      matchLabels:
        testing.upbound.io/example-name: group_match
    userSelector:
      matchLabels:
        testing.upbound.io/example-name: user_1