apiVersion: dds.opentelekomcloud.m.crossplane.io/v1alpha1
kind: BackupV3
metadata:
  annotations:
    meta.upbound.io/example-id: dds/v1alpha1/backupv3
  labels:
    testing.upbound.io/example-name: backup
  name: backup
  namespace: upbound-system
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: ${var.name}
