apiVersion: rds.opentelekomcloud.m.crossplane.io/v1alpha1
kind: PostgresExtensionV3
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/postgresextensionv3
  labels:
    testing.upbound.io/example-name: extension
  name: extension
  namespace: upbound-system
spec:
  forProvider:
    databaseName: ${var.database_name}
    extensionName: hstore
    instanceSelector:
      matchLabels:
        testing.upbound.io/example-name: example
