apiVersion: apigw.opentelekomcloud.m.crossplane.io/v1alpha1
kind: CertificateV2
metadata:
  annotations:
    meta.upbound.io/example-id: apigw/v1alpha1/certificatev2
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    contentSecretRef:
      key: example-key
      name: example-secret
    name: ${var.certificate_name}
    privateKeySecretRef:
      key: example-key
      name: example-secret
