apiVersion: dds.opentelekomcloud.crossplane.io/v1alpha1
kind: PublicIPAssociateV3
metadata:
  annotations:
    meta.upbound.io/example-id: dds/v1alpha1/publicipassociatev3
  labels:
    testing.upbound.io/example-name: public_ip
  name: public-ip
spec:
  forProvider:
    nodeId: ${var.node_id}
    publicIp: ${opentelekomcloud_compute_floatingip_v2.eip.address}
    publicIpId: ${opentelekomcloud_compute_floatingip_v2.eip.id}

---

apiVersion: compute.opentelekomcloud.crossplane.io/v1alpha1
kind: FloatingipV2
metadata:
  annotations:
    meta.upbound.io/example-id: dds/v1alpha1/publicipassociatev3
  labels:
    testing.upbound.io/example-name: eip
  name: eip
spec:
  forProvider: {}
