apiVersion: swr.opentelekomcloud.m.crossplane.io/v1alpha1
kind: OrganizationPermissionsV2
metadata:
  annotations:
    meta.upbound.io/example-id: swr/v1alpha1/organizationpermissionsv2
  labels:
    testing.upbound.io/example-name: swr-org-permissions
  name: swr-op-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    organizationSelector:
      matchLabels:
        testing.upbound.io/example-name: swr-org-permissions-org
    userSelector:
      matchLabels:
        testing.upbound.io/example-name: swr-org-permissions-user
    auth: 3

---
apiVersion: identity.opentelekomcloud.m.crossplane.io/v1alpha1
kind: UserV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/userv3
  labels:
    testing.upbound.io/example-name: swr-org-permissions-user
  name: swr-usr-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    name: swr-usr-${Rand.RFC1123Subdomain}

---
apiVersion: swr.opentelekomcloud.m.crossplane.io/v1alpha1
kind: OrganizationV2
metadata:
  annotations:
    meta.upbound.io/example-id: swr/v1alpha1/organizationv2
  labels:
    testing.upbound.io/example-name: swr-org-permissions-org
  name: swr-org-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    name: swr-org-${Rand.RFC1123Subdomain}
