apiVersion: compute.opentelekomcloud.m.crossplane.io/v1alpha1
kind: KeypairV2
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/keypairv2
  labels:
    testing.upbound.io/example-name: sample-instance
  name: sample-instance
  namespace: test
spec:
  forProvider:
    name: crossplane-keypair
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDTUED6lEQhwmmpqypHQLqGu8xoUzvT8/uHb9c/uSTNq/qk5GN7gOeK8bs9DvPf4BIYBj5CPzhaidVDue+poqfL9su0mZ1K+eldWoGwkmjOB22kiA9vYmKDEG5u+S3S2UxsM+k09Qh8WGGMuvmCRF7KyNf8rlSJns3bsyG0vDjKuo3hdoCQi5RW950VtaAaefRXfQqgk1y8SR2xZKM0e24yICHd1C40tb5RgiNx7s45VHfVY6XMO+eESeHyDEJMr1AoJhkuiziE1feYmLIC2C02wpRXdLxqu2DbrJfqaPWe0J5mZKTXAFzpr/kdReDDp0lgJhjcralcLSZVa1JhQ1iX4n7+v0YKa6WHInnjmeN4PLz8gBanE40OpkZI/DVIWbhX/CrYi+tpZKzYc9ZGdd9UDGPNUNwIMMvat73zp/arAhh9n2nl68/iqM/Xhs8BQ8PYYSuMkhEAZksmSN3Qr6PuE3OpmoHRt+nWwtap751O3JwI8Kmt2iH+I4EOD5cx2CPNjFEOnLLSRqcnQ6CszDfDxDfEAT3wNT/4spM7xqDcvUD523b91fJb1N5NjgmxAmksOxJlrJzTUbVLwLh+RcPd/Lz8kB/NX/peZhcUFLdRbdAUIIgKuEOPBTbFm39Hgj5YVSnSQIkXp6hwO7FSh88ps+8fTPgW01IKr8MG4GhiWQ==

---
apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: VpcV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/v1
  labels:
    testing.upbound.io/example-name: sample-instance
  name: sample-instance
  namespace: test
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    name: crossplane-vpc
    tags:
      managed-by: crossplane
---
apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: SubnetV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/subnetv1
  labels:
    testing.upbound.io/example-name: sample-instance
  name: sample-instance
  namespace: test
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    gatewayIp: "192.168.0.1"
    name: crossplane-subnet
    ntpAddresses: "10.100.0.33,10.100.0.34"
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-instance
    tags:
      managed-by: crossplane

---
apiVersion: cce.opentelekomcloud.m.crossplane.io/v1alpha1
kind: ClusterV3
metadata:
  annotations:
    meta.upbound.io/example-id: cce/v1alpha1/clusterv3
  labels:
    testing.upbound.io/example-name: sample-crossplane-cluster
  name: sample-crossplane-cluster
  namespace: test
spec:
  forProvider:
    authenticationMode: rbac
    clusterType: VirtualMachine
    description: crossplane
    flavorId: cce.s1.small
    containerNetworkType: vpc-router
    name: crossplane-cluster
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-instance
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-instance

---
apiVersion: cce.opentelekomcloud.m.crossplane.io/v1alpha1
kind: NodeV3
metadata:
  annotations:
    meta.upbound.io/example-id: cce/v1alpha1/nodev3
  labels:
    testing.upbound.io/example-name: sample-instance
  name: sample-instance
  namespace: test
spec:
  forProvider:
    availabilityZone: eu-de-01
    bandwidthSize: 100
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-crossplane-cluster
    dataVolumes:
      - size: 100
        volumetype: SSD
      - extendParams:
          useType: docker
        size: 100
        volumetype: SSD
    flavorId: s2.large.2
    keyPairSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-instance
    name: crossplane-node-01
    os: HCE OS 2.0
    rootVolume:
      - size: 40
        volumetype: SSD
    runtime: containerd

---
apiVersion: cce.opentelekomcloud.m.crossplane.io/v1alpha1
kind: NodePoolV3
metadata:
  annotations:
    meta.upbound.io/example-id: cce/v1alpha1/nodepoolv3
  labels:
    testing.upbound.io/example-name: sample-node-pool
  name: sample-node-pool
  namespace: test
spec:
  forProvider:
    availabilityZone: eu-de-01
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-crossplane-cluster
    dataVolumes:
      - size: 100
        volumetype: SSD
      - extendParams:
          useType: docker
        size: 100
        volumetype: SSD
    flavor: s2.xlarge.2
    initialNodeCount: 1
    keyPairSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-instance
    maxNodeCount: 9
    minNodeCount: 1
    name: sample-crossplane-node-pool
    os: HCE OS 2.0
    priority: 1
    rootVolume:
      - size: 40
        volumetype: SSD
    runtime: containerd
    scaleDownCooldownTime: 100
    scaleEnable: true
