apiVersion: identity.opentelekomcloud.crossplane.io/v1alpha1
kind: UserV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/userv3
  labels:
    testing.upbound.io/example-name: user_1
  name: user-1
spec:
  forProvider:
    name: user_1
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
