apiVersion: rds.opentelekomcloud.crossplane.io/v1alpha1
kind: BackupV3
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/backupv3
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance
    name: rds-backup-test-01
