apiVersion: rds.opentelekomcloud.crossplane.io/v1alpha1
kind: ReadReplicaV3
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/readreplicav3
  labels:
    testing.upbound.io/example-name: replica
  name: replica
spec:
  forProvider:
    availabilityZone: ${var.az_replica}
    flavorRef: rds.pg.c2.medium
    name: test-replica
    replicaOfIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance
    volume:
    - type: COMMON

---

apiVersion: rds.opentelekomcloud.crossplane.io/v1alpha1
kind: InstanceV3
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/readreplicav3
  labels:
    testing.upbound.io/example-name: instance
  name: instance
spec:
  forProvider:
    availabilityZone: ${var.az_main}
    backupStrategy:
    - keepDays: 1
      startTime: 08:00-09:00
    computeSecurityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    db:
    - passwordSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      port: "8635"
      type: PostgreSQL
      version: "10"
    flavor: rds.pg.c2.medium
    name: test-instance
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tag:
      created: terraform
    volume:
    - size: 40
      type: ULTRAHIGH
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
