apiVersion: dcs.opentelekomcloud.crossplane.io/v1alpha1
kind: InstanceV1
metadata:
  annotations:
    meta.upbound.io/example-id: dcs/v1alpha1/instancev1
  labels:
    testing.upbound.io/example-name: instance_1
  name: instance-1
spec:
  forProvider:
    availableZones:
    - ${data.opentelekomcloud_dcs_az_v1.az_1.id}
    backupPolicy:
    - backupAt:
      - 1
      - 2
      - 4
      - 6
      backupType: manual
      beginAt: 00:00-01:00
      periodType: weekly
      saveDays: 1
    capacity: 2
    engine: Redis
    engineVersion: "3.0"
    name: test_dcs_instance
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    productId: ${data.opentelekomcloud_dcs_product_v1.product_1.id}
    securityGroupId: ${opentelekomcloud_networking_secgroup_v2.secgroup_1.id}
    subnetId: ${var.network_id}
    tags:
      environment: basic
      managed_by: terraform
    vpcId: ${var.vpc_id}

---

apiVersion: networking.opentelekomcloud.crossplane.io/v1alpha1
kind: SecgroupV2
metadata:
  annotations:
    meta.upbound.io/example-id: dcs/v1alpha1/instancev1
  labels:
    testing.upbound.io/example-name: secgroup_1
  name: secgroup-1
spec:
  forProvider:
    description: secgroup_1
    name: secgroup_1
