apiVersion: rds.crossplane.io/v1alpha1
kind: BackupV3
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/backupv3
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: manual
    instanceId: ${opentelekomcloud_rds_instance_v3.instance.id}
    name: rds-backup-test-01

---

apiVersion: rds.crossplane.io/v1alpha1
kind: InstanceV3
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/backupv3
  labels:
    testing.upbound.io/example-name: instance
  name: instance
spec:
  forProvider:
    datastore: percona
    engine: mysql
    flavor_ref: rds.mysql.s1.large
    name: test-instance
