apiVersion: v1
kind: Secret
metadata:
  name: example-dds-password
  namespace: crossplane-system
type: Opaque
data:
  example-dds-key: UG9zdGdyZXNAIzIwMjQ=

---

apiVersion: vpc.opentelekomcloud.crossplane.io/v1alpha1
kind: VpcV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/v1
  labels:
    testing.upbound.io/example-name: sample-dds-instance
  name: sample-dds-instance
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    name: crossplane-vpc
    tags:
      managed-by: crossplane
---

apiVersion: vpc.opentelekomcloud.crossplane.io/v1alpha1
kind: SubnetV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/subnetv1
  labels:
    testing.upbound.io/example-name: sample-dds-instance
  name: sample-dds-instance
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    gatewayIp: "192.168.0.1"
    name: crossplane-subnet
    ntpAddresses: "10.100.0.33,10.100.0.34"
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-dds-instance
    tags:
      managed-by: crossplane

---

apiVersion: compute.opentelekomcloud.crossplane.io/v1alpha1
kind: SecgroupV2
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/secgroupv2
  labels:
    testing.upbound.io/example-name: sample-dds-instance
  name: sample-dds-instance
spec:
  forProvider:
    description: crossplane security group
    name: crossplane-sg
    rule:
      - cidr: 0.0.0.0/0
        fromPort: 22
        ipProtocol: tcp
        toPort: 22
      - cidr: 0.0.0.0/0
        fromPort: 8080
        ipProtocol: tcp
        toPort: 8080
      - cidr: 0.0.0.0/0
        fromPort: 27017
        ipProtocol: tcp
        toPort: 27017

---

apiVersion: dds.opentelekomcloud.crossplane.io/v1alpha1
kind: InstanceV3
metadata:
  annotations:
    meta.upbound.io/example-id: dds/v1alpha1/instancev3
  labels:
    testing.upbound.io/example-name: sample-dds-instance
  name: sample-dds-instance
spec:
  forProvider:
    availabilityZone: eu-de-01
    datastore:
      - storageEngine: wiredTiger
        type: DDS-Community
        version: "3.4"
    flavor:
      - num: 1
        size: 30
        specCode: dds.mongodb.s2.medium.4.repset
        storage: ULTRAHIGH
        type: replica
    mode: ReplicaSet
    name: crossplane-dds-instance
    passwordSecretRef:
      key: example-dds-key
      name: example-dds-password
      namespace: crossplane-system
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-dds-instance
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-dds-instance
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-dds-instance
    tags:
      managed-by: crossplane

---

apiVersion: dds.opentelekomcloud.crossplane.io/v1alpha1
kind: BackupV3
metadata:
  annotations:
    meta.upbound.io/example-id: dds/v1alpha1/backupv3
  labels:
    testing.upbound.io/example-name: sample-dds-backup
  name: sample-dds-backup
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-dds-instance
    name: crossplane-dds-backup
