apiVersion: obs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: BucketInventory
metadata:
  annotations:
    meta.upbound.io/example-id: obs/v1alpha1/bucketinventory
  labels:
    testing.upbound.io/example-name: inventory
  name: obs-inv-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucket
    configurationId: test-id
    destination:
      - bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: bucket
        format: CSV
        prefix: test-
    filterPrefix: test-filter-prefix
    frequency: Weekly
    includedObjectVersions: Current
    isEnabled: true
    optionalFields:
      - Size
      - LastModifiedDate
      - ReplicationStatus