apiVersion: obs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: BucketObject
metadata:
  annotations:
    meta.upbound.io/example-id: obs/v1alpha1/bucketobject
  labels:
    testing.upbound.io/example-name: obs-object
  name: obs-bobj-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: obs-object-bucket
    content: |
      {"provider_name": "t_cloud_public"}
    contentType: application/json
    key: test_index_json
    encryption: true

---
apiVersion: obs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: obs/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: obs-object-bucket
  name: obs-bkt-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    bucket: obs-bkt-${Rand.RFC1123Subdomain}
    tags:
      Env: Test
      foo: bar
