apiVersion: obs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: BucketPolicy
metadata:
  name: obs-bpol-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: obs-bucketpolicy-dyn-bucket
    policy: |
      {
        "Statement": [{
          "Effect": "Allow",
          "Principal": {"ID": ["*"]},
          "Action": ["GetObject", "PutObject"],
          "Resource": ["${this.bucket}/*"]
        }]
      }

---
apiVersion: obs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: obs/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: obs-bucketpolicy-dyn-bucket
  name: obs-bkt-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    bucket: obs-bkt-${Rand.RFC1123Subdomain}
    tags:
      Env: Test
      foo: bar
