apiVersion: obs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: BucketACL
metadata:
  annotations:
    meta.upbound.io/example-id: obs/v1alpha1/bucketacl
  labels:
    testing.upbound.io/example-name: obs-acl
  name: obs-bacl-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: obs-acl-bucket
    ownerPermission:
      - accessToAcl:
          - READ_ACP
          - WRITE_ACP
        accessToBucket:
          - READ
          - WRITE

---
apiVersion: obs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: obs/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: obs-acl-bucket
  name: obs-bkt-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    bucket: obs-bkt-${Rand.RFC1123Subdomain}
    tags:
      Env: Test
      foo: bar
