apiVersion: obs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: BucketReplication
metadata:
  annotations:
    meta.upbound.io/example-id: obs/v1alpha1/bucketreplication
  labels:
    testing.upbound.io/example-name: test
  name: obs-rpl-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    agencySelector:
      matchLabels:
        testing.upbound.io/example-name: repl-agency
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: repl-source
    destinationBucketSelector:
      matchLabels:
        testing.upbound.io/example-name: repl-dest
    rule:
      - deleteData: false
        historyEnabled: false