apiVersion: waf.opentelekomcloud.m.crossplane.io/v1alpha1
kind: DedicatedInstanceV1
metadata:
  annotations:
    meta.upbound.io/example-id: waf/v1alpha1/dedicatedinstancev1
  labels:
    testing.upbound.io/example-name: wafd_1
  name: wafd-1
  namespace: upbound-system
spec:
  forProvider:
    architecture: x86
    availabilityZone: eu-de-01
    flavor: s2.large.2
    name: wafd-instance-1
    securityGroup:
    - ${data.opentelekomcloud_networking_secgroup_v2.default_secgroup.id}
    specification: waf.instance.professional
    subnetId: ${data.opentelekomcloud_vpc_subnet_v1.shared_subnet.network_id}
    vpcId: ${data.opentelekomcloud_vpc_subnet_v1.shared_subnet.vpc_id}
