apiVersion: er.opentelekomcloud.m.crossplane.io/v1alpha1
kind: StaticRouteV3
metadata:
  annotations:
    meta.upbound.io/example-id: er/v1alpha1/staticroutev3
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    attachmentId: ${var.source_vpc_attachment_id}
    destination: ${var.destination_vpc_cidr}
    routeTableId: ${var.route_table_id}
