apiVersion: waf.opentelekomcloud.crossplane.io/v1alpha1
kind: DedicatedCcRuleV1
metadata:
  annotations:
    meta.upbound.io/example-id: waf/v1alpha1/dedicatedccrulev1
  labels:
    testing.upbound.io/example-name: rule_1
  name: rule-1
spec:
  forProvider:
    action:
    - category: block
      content: '{"error":"forbidden"}'
      contentType: application/json
    limitNum: 10
    limitPeriod: 60
    lockTime: 10
    mode: 0
    policyId: ${opentelekomcloud_waf_dedicated_policy_v1.policy_1.id}
    tagIndex: sessionid
    tagType: cookie
    url: /abc1

---

apiVersion: waf.opentelekomcloud.crossplane.io/v1alpha1
kind: DedicatedPolicyV1
metadata:
  annotations:
    meta.upbound.io/example-id: waf/v1alpha1/dedicatedccrulev1
  labels:
    testing.upbound.io/example-name: policy_1
  name: policy-1
spec:
  forProvider:
    name: policy_cc
