apiVersion: lb.opentelekomcloud.crossplane.io/v1alpha1
kind: IpgroupV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/ipgroupv3
  labels:
    testing.upbound.io/example-name: group_1
  name: group-1
spec:
  forProvider:
    description: group description
    ipList:
    - description: one
      ip: 192.168.50.10
    - description: two
      ip: 192.168.100.10
    - description: three
      ip: 192.168.150.10
    name: group_1
