apiVersion: lb.opentelekomcloud.crossplane.io/v1alpha1
kind: LoadbalancerV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/loadbalancerv3
  labels:
    testing.upbound.io/example-name: lb_1
  name: lb-1
spec:
  forProvider:
    availabilityZones:
    - ${var.az}
    networkIds:
    - ${var.network_id}
    routerId: ${var.router_id}
    tags:
      muh: kuh
