apiVersion: lb.crossplane.io/v1alpha1
kind: MemberV2
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/memberv2
  labels:
    testing.upbound.io/example-name: member1
  name: member1
spec:
  forProvider:
    address: 192.168.199.23
    poolId: ${var.pool_id}
    protocolPort: 8080
    subnetId: ${var.subnet_id}
