apiVersion: lb.crossplane.io/v1alpha1
kind: PoolV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/poolv3
  labels:
    testing.upbound.io/example-name: pool
  name: pool
spec:
  forProvider:
    lbAlgorithm: ROUND_ROBIN
    loadbalancerId: ${opentelekomcloud_lb_loadbalancer_v3.lb.id}
    name: pool_1
    protocol: TCP
    sessionPersistence:
    - persistenceTimeout: "30"
      type: SOURCE_IP

---

apiVersion: lb.crossplane.io/v1alpha1
kind: LoadbalancerV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/poolv3
  labels:
    testing.upbound.io/example-name: lb
  name: lb
spec:
  forProvider:
    availabilityZones:
    - ${var.availability_zone}
    name: loadbalancer_1
    networkIds:
    - ${var.network_id}
    routerId: ${var.router_id}
