apiVersion: lb.opentelekomcloud.m.crossplane.io/v1alpha1
kind: PolicyV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/policyv3
  labels:
    testing.upbound.io/example-name: sample-lb
  name: lb-pol-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    action: REDIRECT_TO_POOL
    listenerSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-lb
    position: 37
    redirectPoolSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-lb

---
apiVersion: lb.opentelekomcloud.m.crossplane.io/v1alpha1
kind: RuleV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/rulev3
  labels:
    testing.upbound.io/example-name: sample-lb
  name: lb-rul-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    compareType: REGEX
    policySelector:
      matchLabels:
        testing.upbound.io/example-name: sample-lb
    type: PATH
    value: ^.+$