apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: VpcV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/v1
  labels:
    testing.upbound.io/example-name: lb-policy-vpc
  name: sample-lb
  namespace: test
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    name: lb-vpc-${Rand.RFC1123Subdomain}
    tags:
      managed-by: crossplane
---
apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: SubnetV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/subnetv1
  labels:
    testing.upbound.io/example-name: lb-policy-subnet
  name: sample-lb
  namespace: test
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    gatewayIp: "192.168.0.1"
    name: lb-stn-${Rand.RFC1123Subdomain}
    ntpAddresses: "10.100.0.33,10.100.0.34"
    vpcSelector:
      matchLabels:
        testing.upbound.io/example-name: lb-policy-vpc
    tags:
      managed-by: crossplane

---
apiVersion: lb.opentelekomcloud.m.crossplane.io/v1alpha1
kind: LoadbalancerV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/loadbalancerv3
  labels:
    testing.upbound.io/example-name: lb-policy-lb
  name: sample-lb
  namespace: test
spec:
  forProvider:
    name: lb-lb-${Rand.RFC1123Subdomain}
    availabilityZones:
      - eu-de-01
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: lb-policy-subnet
    vpcSelector:
      matchLabels:
        testing.upbound.io/example-name: lb-policy-vpc
    tags:
      managed-by: crossplane

---
apiVersion: lb.opentelekomcloud.m.crossplane.io/v1alpha1
kind: ListenerV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/listenerv3
  labels:
    testing.upbound.io/example-name: lb-policy-listener
  name: sample-lb
  namespace: test
spec:
  forProvider:
    name: lb-lis-${Rand.RFC1123Subdomain}
    loadbalancerSelector:
      matchLabels:
        testing.upbound.io/example-name: lb-policy-lb
    protocol: HTTP
    protocolPort: 8080
    tags:
      managed-by: crossplane

---
apiVersion: lb.opentelekomcloud.m.crossplane.io/v1alpha1
kind: PoolV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/memberv3
  labels:
    testing.upbound.io/example-name: lb-policy-pool
  name: sample-lb
  namespace: test
spec:
  forProvider:
    lbAlgorithm: ROUND_ROBIN
    loadbalancerSelector:
      matchLabels:
        testing.upbound.io/example-name: lb-policy-lb
    name: lb-psl-${Rand.RFC1123Subdomain}
    protocol: HTTP

---
apiVersion: lb.opentelekomcloud.m.crossplane.io/v1alpha1
kind: PolicyV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/policyv3
  labels:
    testing.upbound.io/example-name: lb-policy
  name: sample-lb
  namespace: test
spec:
  forProvider:
    action: REDIRECT_TO_POOL
    listenerSelector:
      matchLabels:
        testing.upbound.io/example-name: lb-policy-listener
    position: 37
    redirectPoolSelector:
      matchLabels:
        testing.upbound.io/example-name: lb-policy-pool

---
apiVersion: lb.opentelekomcloud.m.crossplane.io/v1alpha1
kind: RuleV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/rulev3
  labels:
    testing.upbound.io/example-name: lb-rule
  name: sample-lb
  namespace: test
spec:
  forProvider:
    compareType: REGEX
    policySelector:
      matchLabels:
        testing.upbound.io/example-name: lb-policy
    type: PATH
    value: ^.+$
