apiVersion: lb.opentelekomcloud.m.crossplane.io/v1alpha1
kind: MonitorV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/monitorv3
  labels:
    testing.upbound.io/example-name: sample-lb
  name: lb-mon-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    delay: 3
    maxRetries: 5
    maxRetriesDown: 1
    monitorPort: 8080
    poolSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-lb
    timeout: 30
    type: HTTP