// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type GatewayRoutesV2InitParameters struct {

	// Specifies the ID of the dedicated gateway to which the routes belong.
	// Changing this will create a new resource.
	GatewayID *string `json:"gatewayId,omitempty" tf:"gateway_id,omitempty"`

	// Specifies the configuration of the next-hop routes.
	// +listType=set
	Nexthops []*string `json:"nexthops,omitempty" tf:"nexthops,omitempty"`
}

type GatewayRoutesV2Observation struct {

	// Specifies the ID of the dedicated gateway to which the routes belong.
	// Changing this will create a new resource.
	GatewayID *string `json:"gatewayId,omitempty" tf:"gateway_id,omitempty"`

	// The resource ID (gateway ID).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Specifies the configuration of the next-hop routes.
	// +listType=set
	Nexthops []*string `json:"nexthops,omitempty" tf:"nexthops,omitempty"`

	// The region where the dedicated gateway and routes are located.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type GatewayRoutesV2Parameters struct {

	// Specifies the ID of the dedicated gateway to which the routes belong.
	// Changing this will create a new resource.
	// +kubebuilder:validation:Optional
	GatewayID *string `json:"gatewayId,omitempty" tf:"gateway_id,omitempty"`

	// Specifies the configuration of the next-hop routes.
	// +kubebuilder:validation:Optional
	// +listType=set
	Nexthops []*string `json:"nexthops,omitempty" tf:"nexthops,omitempty"`
}

// GatewayRoutesV2Spec defines the desired state of GatewayRoutesV2
type GatewayRoutesV2Spec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GatewayRoutesV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GatewayRoutesV2InitParameters `json:"initProvider,omitempty"`
}

// GatewayRoutesV2Status defines the observed state of GatewayRoutesV2.
type GatewayRoutesV2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GatewayRoutesV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GatewayRoutesV2 is the Schema for the GatewayRoutesV2s API. Manages a APIGW gateway routes resource within OpenTelekomCloud.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,opentelekomcloud}
type GatewayRoutesV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.gatewayId) || (has(self.initProvider) && has(self.initProvider.gatewayId))",message="spec.forProvider.gatewayId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nexthops) || (has(self.initProvider) && has(self.initProvider.nexthops))",message="spec.forProvider.nexthops is a required parameter"
	Spec   GatewayRoutesV2Spec   `json:"spec"`
	Status GatewayRoutesV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GatewayRoutesV2List contains a list of GatewayRoutesV2s
type GatewayRoutesV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayRoutesV2 `json:"items"`
}

// Repository type metadata.
var (
	GatewayRoutesV2_Kind             = "GatewayRoutesV2"
	GatewayRoutesV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GatewayRoutesV2_Kind}.String()
	GatewayRoutesV2_KindAPIVersion   = GatewayRoutesV2_Kind + "." + CRDGroupVersion.String()
	GatewayRoutesV2_GroupVersionKind = CRDGroupVersion.WithKind(GatewayRoutesV2_Kind)
)

func init() {
	SchemeBuilder.Register(&GatewayRoutesV2{}, &GatewayRoutesV2List{})
}
