apiVersion: evs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: SnapshotV2
metadata:
  annotations:
    meta.upbound.io/example-id: evs/v1alpha1/snapshotv2
  labels:
    testing.upbound.io/example-name: test
  name: evs-snp-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    description: crossplane
    metadata:
      foo: bar
    name: evs-snp-${Rand.RFC1123Subdomain}
    volumeSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---
apiVersion: evs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: VolumeV3
metadata:
  annotations:
    meta.upbound.io/example-id: evs/v1alpha1/snapshotv2
  labels:
    testing.upbound.io/example-name: test
  name: evs-vol-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    availabilityZone: eu-de-01
    description: crossplane
    name: evs-vol-${Rand.RFC1123Subdomain}
    size: 12
    volumeType: SAS