apiVersion: evs.opentelekomcloud.m.crossplane.io/v1alpha1
kind: VolumeV3
metadata:
  annotations:
    meta.upbound.io/example-id: evs/v1alpha1/volumev3
  labels:
    testing.upbound.io/example-name: evs-volume
  name: evs-vol-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    availabilityZone: eu-de-01
    description: crossplane
    name: evs-vol-${Rand.RFC1123Subdomain}
    size: 20
    tags:
      foo: bar
      key: value
    volumeType: SAS
    kmsSelector:
      matchLabels:
        testing.upbound.io/example-name: evs-volume-key
---
apiVersion: kms.opentelekomcloud.m.crossplane.io/v1alpha1
kind: KeyV1
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1alpha1/keyv1
  labels:
    testing.upbound.io/example-name: evs-volume-key
  name: evs-key-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    isEnabled: true
    keyAlias: evs-key-${Rand.RFC1123Subdomain}
    keyDescription: crossplane
    pendingDays: "7"
    realm: eu-de
    tags:
      muh: kuh
