apiVersion: compute.opentelekomcloud.crossplane.io/v1alpha1
kind: KeypairV2
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/keypairv2
  labels:
    testing.upbound.io/example-name: sample-instance
  name: sample-instance
spec:
  forProvider:
    name: crossplane-keypair
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDTUED6lEQhwmmpqypHQLqGu8xoUzvT8/uHb9c/uSTNq/qk5GN7gOeK8bs9DvPf4BIYBj5CPzhaidVDue+poqfL9su0mZ1K+eldWoGwkmjOB22kiA9vYmKDEG5u+S3S2UxsM+k09Qh8WGGMuvmCRF7KyNf8rlSJns3bsyG0vDjKuo3hdoCQi5RW950VtaAaefRXfQqgk1y8SR2xZKM0e24yICHd1C40tb5RgiNx7s45VHfVY6XMO+eESeHyDEJMr1AoJhkuiziE1feYmLIC2C02wpRXdLxqu2DbrJfqaPWe0J5mZKTXAFzpr/kdReDDp0lgJhjcralcLSZVa1JhQ1iX4n7+v0YKa6WHInnjmeN4PLz8gBanE40OpkZI/DVIWbhX/CrYi+tpZKzYc9ZGdd9UDGPNUNwIMMvat73zp/arAhh9n2nl68/iqM/Xhs8BQ8PYYSuMkhEAZksmSN3Qr6PuE3OpmoHRt+nWwtap751O3JwI8Kmt2iH+I4EOD5cx2CPNjFEOnLLSRqcnQ6CszDfDxDfEAT3wNT/4spM7xqDcvUD523b91fJb1N5NjgmxAmksOxJlrJzTUbVLwLh+RcPd/Lz8kB/NX/peZhcUFLdRbdAUIIgKuEOPBTbFm39Hgj5YVSnSQIkXp6hwO7FSh88ps+8fTPgW01IKr8MG4GhiWQ==

---

apiVersion: vpc.opentelekomcloud.crossplane.io/v1alpha1
kind: V1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/v1
  labels:
    testing.upbound.io/example-name: sample-instance
  name: sample-instance
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    name: crossplane-vpc
    tags:
      managed-by: crossplane
---

apiVersion: vpc.opentelekomcloud.crossplane.io/v1alpha1
kind: SubnetV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/subnetv1
  labels:
    testing.upbound.io/example-name: sample-instance
  name: sample-instance
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    gatewayIp: "192.168.0.1"
    name: crossplane-subnet
    ntpAddresses: "10.100.0.33,10.100.0.34"
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-instance
    tags:
      managed-by: crossplane

---

apiVersion: compute.opentelekomcloud.crossplane.io/v1alpha1
kind: SecgroupV2
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/secgroupv2
  labels:
    testing.upbound.io/example-name: sample-instance
  name: sample-instance
spec:
  forProvider:
    description: crossplane security group
    name: crossplane-sg
    rule:
      - cidr: 0.0.0.0/0
        fromPort: 22
        ipProtocol: tcp
        toPort: 22
      - cidr: 0.0.0.0/0
        fromPort: 8080
        ipProtocol: tcp
        toPort: 8080

---

apiVersion: ecs.opentelekomcloud.crossplane.io/v1alpha1
kind: InstanceV1
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/instancev1
  labels:
    testing.upbound.io/example-name: sample-instance
  name: sample-instance
spec:
  forProvider:
    availabilityZone: eu-de-01
    flavor: s2.large.2
    imageId: 54c617ad-5c85-4426-b721-494a9c7719c2
    keyNameSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-instance
    computeSecurityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-instance
    name: server_1
    nics:
      - networkIdSelector:
          matchLabels:
            testing.upbound.io/example-name: sample-instance
    tags:
      muh: kuh
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-instance