apiVersion: dis.opentelekomcloud.crossplane.io/v1alpha1
kind: CheckpointV2
metadata:
  annotations:
    meta.upbound.io/example-id: dis/v1alpha1/checkpointv2
  labels:
    testing.upbound.io/example-name: checkpoint_1
  name: checkpoint-1
spec:
  forProvider:
    appNameSelector:
      matchLabels:
        testing.upbound.io/example-name: app_1
    metadata: my_first_checkpoint
    partitionId: "0"
    sequenceNumber: "0"
    streamNameSelector:
      matchLabels:
        testing.upbound.io/example-name: stream_1

---

apiVersion: dis.opentelekomcloud.crossplane.io/v1alpha1
kind: AppV2
metadata:
  annotations:
    meta.upbound.io/example-id: dis/v1alpha1/checkpointv2
  labels:
    testing.upbound.io/example-name: app_1
  name: app-1
spec:
  forProvider:
    name: my_app

---

apiVersion: dis.opentelekomcloud.crossplane.io/v1alpha1
kind: StreamV2
metadata:
  annotations:
    meta.upbound.io/example-id: dis/v1alpha1/checkpointv2
  labels:
    testing.upbound.io/example-name: stream_1
  name: stream-1
spec:
  forProvider:
    autoScaleMaxPartitionCount: 4
    autoScaleMinPartitionCount: 1
    compressionFormat: zip
    dataType: BLOB
    name: my_stream
    partitionCount: 3
    retentionPeriod: 24
    streamType: COMMON
    tags:
      foo: bar
