apiVersion: dms.opentelekomcloud.m.crossplane.io/v1alpha1
kind: InstanceV1
metadata:
  annotations:
    meta.upbound.io/example-id: dms/v1alpha1/instancev1
  labels:
    testing.upbound.io/example-name: instance_1
  name: instance-1
  namespace: upbound-system
spec:
  forProvider:
    accessUser: ${var.access_user}
    availableZones:
    - ${data.opentelekomcloud_dms_az_v1.az_1.id}
    engine: kafka
    engineVersion: ${data.opentelekomcloud_dms_product_v1.product_1.version}
    name: kafka-test
    partitionNum: ${data.opentelekomcloud_dms_product_v1.product_1.partition_num}
    passwordSecretRef:
      key: example-key
      name: example-secret
    productId: ${data.opentelekomcloud_dms_product_v1.product_1.id}
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: secgroup_1
    specification: ${data.opentelekomcloud_dms_product_v1.product_1.bandwidth}
    storageSpace: ${data.opentelekomcloud_dms_product_v1.product_1.storage}
    storageSpecCode: ${data.opentelekomcloud_dms_product_v1.product_1.storage_spec_code}
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: networking.opentelekomcloud.m.crossplane.io/v1alpha1
kind: SecgroupV2
metadata:
  annotations:
    meta.upbound.io/example-id: dms/v1alpha1/instancev1
  labels:
    testing.upbound.io/example-name: secgroup_1
  name: secgroup-1
  namespace: upbound-system
spec:
  forProvider:
    description: secgroup_1
    name: secgroup_1
