apiVersion: dms.opentelekomcloud.m.crossplane.io/v1alpha1
kind: SmartConnectTaskActionV2
metadata:
  annotations:
    meta.upbound.io/example-id: dms/v1alpha1/smartconnecttaskactionv2
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    action: pause
    instanceId: ${var.instance_id}
    taskId: ${var.task_id}
