apiVersion: obs.opentelekomcloud.crossplane.io/v1alpha1
kind: BucketPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: obs/v1alpha1/bucketpolicy
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    bucket: ${opentelekomcloud_obs_bucket.bucket.id}
    policy: my-tf-test-bucket

---

apiVersion: obs.opentelekomcloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: obs/v1alpha1/bucketpolicy
  labels:
    testing.upbound.io/example-name: bucket
  name: bucket
spec:
  forProvider:
    bucket: my-tf-test-bucket
