apiVersion: networking.opentelekomcloud.m.crossplane.io/v1alpha1
kind: RouterInterfaceV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/routerinterfacev2
  labels:
    testing.upbound.io/example-name: router_interface
  name: ntw-ri-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    routerSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-router
    subnetSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-subnet