apiVersion: swr.opentelekomcloud.crossplane.io/v1alpha1
kind: RepositoryV2
metadata:
  annotations:
    meta.upbound.io/example-id: swr/v1alpha1/repositoryv2
  labels:
    testing.upbound.io/example-name: repo_1
  name: repo-1
spec:
  forProvider:
    category: linux
    description: Test repository
    isPublic: false
    name: repository_1
    organization: organization_1

---

apiVersion: swr.opentelekomcloud.crossplane.io/v1alpha1
kind: OrganizationV2
metadata:
  annotations:
    meta.upbound.io/example-id: swr/v1alpha1/repositoryv2
  labels:
    testing.upbound.io/example-name: org_1
  name: org-1
spec:
  forProvider:
    name: organization_1
