apiVersion: waf.opentelekomcloud.crossplane.io/v1alpha1
kind: DedicatedPreciseProtectionRuleV1
metadata:
  annotations:
    meta.upbound.io/example-id: waf/v1alpha1/dedicatedpreciseprotectionrulev1
  labels:
    testing.upbound.io/example-name: rule_1
  name: rule-1
spec:
  forProvider:
    action:
    - category: block
    conditions:
    - category: url
      contents:
      - test
      logicOperation: contain
    description: desc
    policyId: ${opentelekomcloud_waf_dedicated_policy_v1.policy_1.id}
    priority: 50
    time: false

---

apiVersion: waf.opentelekomcloud.crossplane.io/v1alpha1
kind: DedicatedPolicyV1
metadata:
  annotations:
    meta.upbound.io/example-id: waf/v1alpha1/dedicatedpreciseprotectionrulev1
  labels:
    testing.upbound.io/example-name: policy_1
  name: policy-1
spec:
  forProvider:
    name: policy_pp
