apiVersion: waf.opentelekomcloud.crossplane.io/v1alpha1
kind: DedicatedKnownAttackSourceRuleV1
metadata:
  annotations:
    meta.upbound.io/example-id: waf/v1alpha1/dedicatedknownattacksourcerulev1
  labels:
    testing.upbound.io/example-name: rule_1
  name: rule-1
spec:
  forProvider:
    blockTime: 300
    category: long_cookie_block
    description: test description
    policyId: ${opentelekomcloud_waf_dedicated_policy_v1.policy_1.id}

---

apiVersion: waf.opentelekomcloud.crossplane.io/v1alpha1
kind: DedicatedPolicyV1
metadata:
  annotations:
    meta.upbound.io/example-id: waf/v1alpha1/dedicatedknownattacksourcerulev1
  labels:
    testing.upbound.io/example-name: policy_1
  name: policy-1
spec:
  forProvider:
    name: policy_ka
