apiVersion: networking.opentelekomcloud.m.crossplane.io/v1alpha1
kind: NetworkV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/routerinterfacev2
  labels:
    testing.upbound.io/example-name: compute-network
  name: com-net-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    adminStateUp: "true"
    name: com-net-${Rand.RFC1123Subdomain}
---
apiVersion: networking.opentelekomcloud.m.crossplane.io/v1alpha1
kind: RouterV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/routerinterfacev2
  labels:
    testing.upbound.io/example-name: compute-router
  name: com-rtr-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    name: com-rtr-${Rand.RFC1123Subdomain}

---
apiVersion: networking.opentelekomcloud.m.crossplane.io/v1alpha1
kind: SubnetV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/routerinterfacev2
  labels:
    testing.upbound.io/example-name: compute-subnet
  name: com-stn-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    name: com-stn-${Rand.RFC1123Subdomain}
    cidr: 192.168.199.0/24
    ipVersion: 4
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: compute-network

---
apiVersion: networking.opentelekomcloud.m.crossplane.io/v1alpha1
kind: RouterInterfaceV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/routerinterfacev2
  labels:
    testing.upbound.io/example-name: compute-router-interface
  name: com-ri-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    routerSelector:
      matchLabels:
        testing.upbound.io/example-name: compute-router
    subnetSelector:
      matchLabels:
        testing.upbound.io/example-name: compute-subnet

---
apiVersion: compute.opentelekomcloud.m.crossplane.io/v1alpha1
kind: FloatingipAssociateV2
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/floatingipassociatev2
  labels:
    testing.upbound.io/example-name: compute-fip-associate
  name: com-fip-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    floatingIpSelector:
      matchLabels:
        testing.upbound.io/example-name: compute-fip
    instanceSelector:
      matchLabels:
        testing.upbound.io/example-name: compute-instance
---
apiVersion: compute.opentelekomcloud.m.crossplane.io/v1alpha1
kind: InstanceV2
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/floatingipassociatev2
  labels:
    testing.upbound.io/example-name: compute-instance
  name: com-vm-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    flavorId: s2.large.2
    imageId: 765aeae4-7c4a-4bc7-93ff-ad1daa9c2fda
    name: com-vm-${Rand.RFC1123Subdomain}
    network:
      - nameSelector:
          matchLabels:
            testing.upbound.io/example-name: compute-network

---
apiVersion: networking.opentelekomcloud.m.crossplane.io/v1alpha1
kind: FloatingipV2
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/floatingipassociatev2
  labels:
    testing.upbound.io/example-name: compute-fip
  name: com-fip-${Rand.RFC1123Subdomain}
  namespace: test
spec:
  forProvider:
    pool: admin_external_net
