apiVersion: obs.opentelekomcloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: obs/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: b
  name: b
spec:
  forProvider:
    acl: private
    bucket: my-tf-test-bucket
    tags:
      Env: Test
      foo: bar
