apiVersion: v1
kind: Secret
metadata:
  name: example-rds-secret
  namespace: test
type: Opaque
data:
  example-rds-key: ${data.rdsKey}

---
apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: VpcV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/v1
  labels:
    testing.upbound.io/example-name: sample-rds-instance
  name: sample-rds-instance
  namespace: test
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    name: crossplane-rds-vpc
    tags:
      managed-by: crossplane
---
apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: SubnetV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/subnetv1
  labels:
    testing.upbound.io/example-name: sample-rds-instance
  name: sample-rds-instance
  namespace: test
spec:
  forProvider:
    cidr: "192.168.0.0/16"
    gatewayIp: "192.168.0.1"
    name: crossplane-rds-subnet
    ntpAddresses: "10.100.0.33,10.100.0.34"
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-rds-instance
    tags:
      managed-by: crossplane

---
apiVersion: compute.opentelekomcloud.m.crossplane.io/v1alpha1
kind: SecgroupV2
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/secgroupv2
  labels:
    testing.upbound.io/example-name: sample-rds-instance
  name: sample-rds-instance
  namespace: test
spec:
  forProvider:
    description: crossplane security group
    name: crossplane-rds-sg
    rule:
      - cidr: 0.0.0.0/0
        fromPort: 8635
        ipProtocol: tcp
        toPort: 8635
      - cidr: 0.0.0.0/0
        fromPort: 8080
        ipProtocol: tcp
        toPort: 8080
      - cidr: 0.0.0.0/0
        fromPort: 443
        ipProtocol: tcp
        toPort: 443

---
apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
kind: EIPV1
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/eipv1
  labels:
    testing.upbound.io/example-name: sample-rds-instance
  name: sample-rds-instance
  namespace: test
spec:
  forProvider:
    bandwidth:
      - chargeMode: traffic
        name: crossplane-rds-instance
        shareType: PER
        size: 8
    publicip:
      - type: 5_bgp

---
apiVersion: rds.opentelekomcloud.m.crossplane.io/v1alpha1
kind: InstanceV3
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/instancev3
  labels:
    testing.upbound.io/example-name: sample-rds-instance
  name: sample-rds-instance
  namespace: test
spec:
  forProvider:
    availabilityZone:
      - eu-de-03
    backupStrategy:
      - keepDays: 1
        startTime: 08:00-09:00
    db:
      - passwordSecretRef:
          key: example-rds-key
          name: example-rds-secret
        port: 8635
        type: PostgreSQL
        version: "15"
    flavor: rds.pg.n1.large.2
    name: crossplane-rds-instance
    computeSecurityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-rds-instance
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-rds-instance
    tags:
      managed-by: crossplane
    volume:
      - size: 100
        type: CLOUDSSD
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-rds-instance
    publicIpsSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-rds-instance
