apiVersion: fgs.opentelekomcloud.crossplane.io/v1alpha1
kind: FunctionV2
metadata:
  annotations:
    meta.upbound.io/example-id: fgs/v1alpha1/functionv2
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    agency: ${var.agency_name}
    app: default
    codeType: inline
    description: fuction test
    funcCode: ${base64encode(var.function_codes)}
    handler: test.handler
    memorySize: 128
    name: ${var.function_name}
    runtime: Python2.7
    timeout: 3
