apiVersion: smn.opentelekomcloud.crossplane.io/v1alpha1
kind: TopicV2
metadata:
  annotations:
    meta.upbound.io/example-id: smn/v1alpha1/topicv2
  labels:
    testing.upbound.io/example-name: topic_1
  name: topic-1
spec:
  forProvider:
    displayName: The display name of topic_1
    name: topic_1
    tags:
      foo: bar
      key: value
