// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ClusterRestartV1InitParameters struct {

	// Specifies the ID of the CSS cluster.
	// Changing this creates a new resource.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`
}

type ClusterRestartV1Observation struct {

	// Specifies the ID of the CSS cluster.
	// Changing this creates a new resource.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// The resource ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The region in which the resource created.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type ClusterRestartV1Parameters struct {

	// Specifies the ID of the CSS cluster.
	// Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`
}

// ClusterRestartV1Spec defines the desired state of ClusterRestartV1
type ClusterRestartV1Spec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ClusterRestartV1Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterRestartV1InitParameters `json:"initProvider,omitempty"`
}

// ClusterRestartV1Status defines the observed state of ClusterRestartV1.
type ClusterRestartV1Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClusterRestartV1Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ClusterRestartV1 is the Schema for the ClusterRestartV1s API. Manages CSS cluster restart resource within OpenTelekomCloud.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,opentelekomcloud}
type ClusterRestartV1 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterId) || (has(self.initProvider) && has(self.initProvider.clusterId))",message="spec.forProvider.clusterId is a required parameter"
	Spec   ClusterRestartV1Spec   `json:"spec"`
	Status ClusterRestartV1Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterRestartV1List contains a list of ClusterRestartV1s
type ClusterRestartV1List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterRestartV1 `json:"items"`
}

// Repository type metadata.
var (
	ClusterRestartV1_Kind             = "ClusterRestartV1"
	ClusterRestartV1_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClusterRestartV1_Kind}.String()
	ClusterRestartV1_KindAPIVersion   = ClusterRestartV1_Kind + "." + CRDGroupVersion.String()
	ClusterRestartV1_GroupVersionKind = CRDGroupVersion.WithKind(ClusterRestartV1_Kind)
)

func init() {
	SchemeBuilder.Register(&ClusterRestartV1{}, &ClusterRestartV1List{})
}
