// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type GroupV2InitParameters struct {
	GroupAlias *string `json:"groupAlias,omitempty" tf:"group_alias,omitempty"`

	// Specifies the log group name. Changing this parameter will create a new resource.
	GroupName *string `json:"groupName,omitempty" tf:"group_name,omitempty"`

	// Specifies the log expiration time(days).
	// The value is range from 1 to 365.
	TTLInDays *float64 `json:"ttlInDays,omitempty" tf:"ttl_in_days,omitempty"`

	// Specifies the key/value pairs to associate with the log group.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type GroupV2Observation struct {

	// The creation time of the log group.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Shows the enterprise project ID to which the log group belongs.
	EnterpriseProjectID *string `json:"enterpriseProjectId,omitempty" tf:"enterprise_project_id,omitempty"`

	GroupAlias *string `json:"groupAlias,omitempty" tf:"group_alias,omitempty"`

	// Specifies the log group name. Changing this parameter will create a new resource.
	GroupName *string `json:"groupName,omitempty" tf:"group_name,omitempty"`

	// The log group ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Shows the region in the log group resource created.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the log expiration time(days).
	// The value is range from 1 to 365.
	TTLInDays *float64 `json:"ttlInDays,omitempty" tf:"ttl_in_days,omitempty"`

	// Specifies the key/value pairs to associate with the log group.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type GroupV2Parameters struct {

	// +kubebuilder:validation:Optional
	GroupAlias *string `json:"groupAlias,omitempty" tf:"group_alias,omitempty"`

	// Specifies the log group name. Changing this parameter will create a new resource.
	// +kubebuilder:validation:Optional
	GroupName *string `json:"groupName,omitempty" tf:"group_name,omitempty"`

	// Specifies the log expiration time(days).
	// The value is range from 1 to 365.
	// +kubebuilder:validation:Optional
	TTLInDays *float64 `json:"ttlInDays,omitempty" tf:"ttl_in_days,omitempty"`

	// Specifies the key/value pairs to associate with the log group.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// GroupV2Spec defines the desired state of GroupV2
type GroupV2Spec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GroupV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GroupV2InitParameters `json:"initProvider,omitempty"`
}

// GroupV2Status defines the observed state of GroupV2.
type GroupV2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GroupV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GroupV2 is the Schema for the GroupV2s API. Manages a LTS Log Group resource within OpenTelekomCloud.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,opentelekomcloud}
type GroupV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.groupName) || (has(self.initProvider) && has(self.initProvider.groupName))",message="spec.forProvider.groupName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ttlInDays) || (has(self.initProvider) && has(self.initProvider.ttlInDays))",message="spec.forProvider.ttlInDays is a required parameter"
	Spec   GroupV2Spec   `json:"spec"`
	Status GroupV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupV2List contains a list of GroupV2s
type GroupV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GroupV2 `json:"items"`
}

// Repository type metadata.
var (
	GroupV2_Kind             = "GroupV2"
	GroupV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GroupV2_Kind}.String()
	GroupV2_KindAPIVersion   = GroupV2_Kind + "." + CRDGroupVersion.String()
	GroupV2_GroupVersionKind = CRDGroupVersion.WithKind(GroupV2_Kind)
)

func init() {
	SchemeBuilder.Register(&GroupV2{}, &GroupV2List{})
}
